bootstrap.servers=pkc-7prvp.centralindia.azure.confluent.cloud:9092
security.protocol=SASL_SSL
sasl.mechanism=PLAIN
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="PAZR2XDZVGDJER3K" secret="cfltRWP59s83WBI9d5xTVZ7QeaR8my4BU82mqVFzp9Jizmi1aJiLojGXZazwmCqg";
